name: logger
channels:
  - defaults
dependencies:
  - python=3.14
  - pip
  - pip:
      - matplotlib==3.10.9
      - mcp
      - nidaqmx==1.5.0
      - numpy==2.4.5
      - pandas==3.0.3
      - pyinstaller
